name: Deploy to Stage

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm ci

      - name: Build app
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm run build

      - name: Deploy to S3
        run: aws s3 sync codebase/rdicidr-0.1.0/build/ s3://fsl-devops-stage --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1
